info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

spring:
  thymeleaf:
    cache: false
  messages:
    cacheSeconds: 0

jsondoc:
  version: 1.0
  packages[0]: at.porscheinformatik.tutorial.todo
  basePath: http://localhost:8080
  playgroundEnabled: true
  displayMethodAs: URI